# Docker Environment Configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://postgres:5432/static_data_platform_dev}
    username: ${SPRING_DATASOURCE_USERNAME:sdp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
    driver-class-name: org.postgresql.Driver
  
  # JPA Docker Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  
  # Redis Docker Settings
  data:
    redis:
      host: redis
      port: 6379
      timeout: 60000
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

# Logging Docker Settings
logging:
  level:
    com.staticdata.platform: INFO
    org.springframework.web: INFO
    org.springframework.security: WARN
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: /app/logs/application.log

# Security Docker Settings
app:
  jwt:
    secret: ${APP_JWT_SECRET:devSecretKey1234567890123456789012345678901234567890123456789012345678901234567890}
    expiration: ${APP_JWT_EXPIRATION:86400000}
  
  # CORS Docker Settings
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  
  # Docker Features
  audit:
    enabled: true
