# Development Environment Configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/static_data_platform_dev}
    username: ${SPRING_DATASOURCE_USERNAME:sdp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
  
  # JPA Development Settings
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  
  # Development Features
  devtools:
    restart:
      enabled: true
    livereload:
      enabled: true

# Logging Development Settings
logging:
  level:
    com.staticdata.platform: DEBUG
    org.springframework.web: DEBUG
    org.springframework.security: DEBUG

# Security Development Settings
app:
  jwt:
    secret: ${APP_JWT_SECRET:devSecretKey1234567890123456789012345678901234567890123456789012345678901234567890}
    expiration: ${APP_JWT_EXPIRATION:86400000}
  
  # CORS Development Settings
  security:
    cors:
      allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:5173}
  
  # Development Features
  audit:
    enabled: true