# Test Environment Configuration
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/static_data_platform_test}
    username: ${SPRING_DATASOURCE_USERNAME:sdp_user}
    password: ${SPRING_DATASOURCE_PASSWORD:dev_password}
  
  # JPA Test Settings
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
  
  # Test Features
  devtools:
    restart:
      enabled: false

# Logging Test Settings
logging:
  level:
    com.staticdata.platform: INFO
    org.springframework.security: WARN

# Security Test Settings
app:
  jwt:
    secret: ${APP_JWT_SECRET:testSecretKey123456789012345678901234567890}
    expiration: ${APP_JWT_EXPIRATION:3600000}
  
  # Test Features
  audit:
    enabled: false